name: Build Zig
run-name: Build Zig ${{inputs.version}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Zig Release version:"
        default: "0.15.1"
        required: true

permissions:
  contents: write
  actions: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-freebsd-none, arm-freebsd-eabihf, powerpc64-freebsd-none, powerpc64le-freebsd-none, riscv64-freebsd-none, x86_64-freebsd-none, aarch64-linux-musl, aarch64_be-linux-musl, arm-linux-musleabi, arm-linux-musleabihf, armeb-linux-musleabi, armeb-linux-musleabihf, hexagon-linux-musl, loongarch64-linux-musl, loongarch64-linux-muslsf, mips-linux-musleabi, mips-linux-musleabihf, mips64-linux-muslabi64, mips64-linux-muslabin32, mips64el-linux-muslabi64, mips64el-linux-muslabin32, mipsel-linux-musleabi, mipsel-linux-musleabihf, powerpc-linux-musleabi, powerpc-linux-musleabihf, powerpc64-linux-musl, powerpc64le-linux-musl, riscv32-linux-musl, riscv64-linux-musl, s390x-linux-musl, thumb-linux-musleabi, thumb-linux-musleabihf, thumbeb-linux-musleabi, thumbeb-linux-musleabihf, x86-linux-musl, x86_64-linux-musl, x86_64-linux-muslx32, aarch64-macos-none, x86_64-macos-none, aarch64-netbsd-none, aarch64_be-netbsd-none, arm-netbsd-eabi, arm-netbsd-eabihf, armeb-netbsd-eabi, armeb-netbsd-eabihf, mips-netbsd-eabi, mips-netbsd-eabihf, mipsel-netbsd-eabi, mipsel-netbsd-eabihf, powerpc-netbsd-eabi, powerpc-netbsd-eabihf, riscv32-netbsd-none, riscv64-netbsd-none, x86-netbsd-none, x86_64-netbsd-none]
    runs-on: ubuntu-24.04
    env:
      ROOTDIR: ${{github.workspace}}
      ZIG_TARGET: ${{matrix.target}}
    steps:
      - name: Checkout zig-custom
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{inputs.version}}
          use-cache: false

      - name: Get and Patch zig-bootstrap
        run: |
          ZIG_CLANG_VERSION_CMD="zig cc --version"
          ZIG_BOOTSTRAP_REV=$($ZIG_CLANG_VERSION_CMD | sed -E 's/.*zig-bootstrap ([a-f0-9]{40}).*/\1/' | head -n 1)

          curl -LkSs https://github.com/ziglang/zig-bootstrap/archive/${ZIG_BOOTSTRAP_REV}.tar.gz | gzip -d | tar -x
          mv zig-bootstrap-${ZIG_BOOTSTRAP_REV} zig-bootstrap
          cp -R ${{github.workspace}}/lib zig-bootstrap/zig

      - name: Build Zig
        run: |
          cd zig-bootstrap
          ./build ${ZIG_TARGET} baseline
