name: Build Zig
run-name: Build Zig ${{inputs.version}}
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Zig Release version:"
        default: "0.15.1"
        required: true

permissions:
  contents: write
  actions: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-linux-musl]
    runs-on: ubuntu-24.04
    env:
      ROOTDIR: ${{github.workspace}}
      ZIG_TARGET: ${{matrix.target}}
    steps:
      - name: Checkout zig-custom
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{inputs.version}}
          use-cache: false

      - name: Get and Patch zig-bootstrap
        run: |
          ZIG_CLANG_VERSION_CMD="zig cc --version"
          ZIG_BOOTSTRAP_REV=$($ZIG_CLANG_VERSION_CMD | sed -E 's/.*zig-bootstrap ([a-f0-9]{40}).*/\1/' | head -n 1)

          curl -LkSs https://github.com/ziglang/zig-bootstrap/archive/${ZIG_BOOTSTRAP_REV}.tar.gz | gzip -d | tar -x
          mv zig-bootstrap-${ZIG_BOOTSTRAP_REV} zig-bootstrap
          cp -R ${{github.workspace}}/pacthes/lib zig-bootstrap/zig

      - name: Build Zig
        run: |
          cd zig-bootstrap
          ./build ${ZIG_TARGET} baseline
