name: Build Zig
on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [aarch64-linux-musl]
    runs-on: ubuntu-24.04
    env:
      ROOTDIR: ${{github.workspace}}
      ZIG_TARGET: ${{matrix.target}}
    steps:
      - name: Checkout zig-custom
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}

      - name: Get and Patch zig-bootstrap
        run: |
          ZIG_BOOTSTRAP_TARBALL_LINK=$(curl -LkSs https://ziglang.org/download | sed -n 's/.*href="\([^"]*zig-bootstrap[^"]*\.tar\.xz\)".*/\1/p'| head -n1)
          ZIG_BOOTSTRAP_TARBALL_NAME=$(basename $ZIG_BOOTSTRAP_TARBALL_LINK | xargs basename | sed 's/\.tar\.xz$//')
          curl -LkSs $ZIG_BOOTSTRAP_TARBALL_LINK | xz -d | tar -x
          mv $ZIG_BOOTSTRAP_TARBALL_NAME zig-bootstrap
          cp -R ${{github.workspace}}/patches/lib zig-bootstrap/zig

      - name: Build Zig
        run: |
          cd zig-bootstrap
          ./build $ZIG_TARGET baseline
